# Setup
title:               HLCGN
tagline:             'Hansen Lab Computational Genomics Notes'
description:         'Helpful notes for computational analysis of 3D genomics data.'
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate
