# Setup
title:               james' quicknotes
tagline:             'resource for computational biology'
description:         'This website contains my personal collection of notes for computational biology, especially for 3D genomics analyses.'
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate
